//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace Yannyo.SOAP.bdu9erpDataEngineRe {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataEngineSoap", Namespace="Yannyo_Erp_DataEngine")]
    public partial class DataEngine : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductOrderListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoresListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataEngine() {
            this.Url = global::Yannyo.SOAP.Properties.Settings.Default.Yannyo_SOAP_bdu9erpDataEngine_DataEngine;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductListCompletedEventHandler GetProductListCompleted;
        
        /// <remarks/>
        public event GetProductOrderListCompletedEventHandler GetProductOrderListCompleted;
        
        /// <remarks/>
        public event GetOrderListCompletedEventHandler GetOrderListCompleted;
        
        /// <remarks/>
        public event GetStoresListCompletedEventHandler GetStoresListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Yannyo_Erp_DataEngine/GetProductList", RequestNamespace="Yannyo_Erp_DataEngine", ResponseNamespace="Yannyo_Erp_DataEngine", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetProductList(string cCode, string tSQL) {
            object[] results = this.Invoke("GetProductList", new object[] {
                        cCode,
                        tSQL});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductListAsync(string cCode, string tSQL) {
            this.GetProductListAsync(cCode, tSQL, null);
        }
        
        /// <remarks/>
        public void GetProductListAsync(string cCode, string tSQL, object userState) {
            if ((this.GetProductListOperationCompleted == null)) {
                this.GetProductListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductListOperationCompleted);
            }
            this.InvokeAsync("GetProductList", new object[] {
                        cCode,
                        tSQL}, this.GetProductListOperationCompleted, userState);
        }
        
        private void OnGetProductListOperationCompleted(object arg) {
            if ((this.GetProductListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductListCompleted(this, new GetProductListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Yannyo_Erp_DataEngine/GetProductOrderList", RequestNamespace="Yannyo_Erp_DataEngine", ResponseNamespace="Yannyo_Erp_DataEngine", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetProductOrderList(string cCode, int ProduceID, int OrderType, System.DateTime bDate, System.DateTime eDate) {
            object[] results = this.Invoke("GetProductOrderList", new object[] {
                        cCode,
                        ProduceID,
                        OrderType,
                        bDate,
                        eDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductOrderListAsync(string cCode, int ProduceID, int OrderType, System.DateTime bDate, System.DateTime eDate) {
            this.GetProductOrderListAsync(cCode, ProduceID, OrderType, bDate, eDate, null);
        }
        
        /// <remarks/>
        public void GetProductOrderListAsync(string cCode, int ProduceID, int OrderType, System.DateTime bDate, System.DateTime eDate, object userState) {
            if ((this.GetProductOrderListOperationCompleted == null)) {
                this.GetProductOrderListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductOrderListOperationCompleted);
            }
            this.InvokeAsync("GetProductOrderList", new object[] {
                        cCode,
                        ProduceID,
                        OrderType,
                        bDate,
                        eDate}, this.GetProductOrderListOperationCompleted, userState);
        }
        
        private void OnGetProductOrderListOperationCompleted(object arg) {
            if ((this.GetProductOrderListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductOrderListCompleted(this, new GetProductOrderListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Yannyo_Erp_DataEngine/GetOrderList", RequestNamespace="Yannyo_Erp_DataEngine", ResponseNamespace="Yannyo_Erp_DataEngine", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrderList(string cCode, string OrderStr) {
            object[] results = this.Invoke("GetOrderList", new object[] {
                        cCode,
                        OrderStr});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderListAsync(string cCode, string OrderStr) {
            this.GetOrderListAsync(cCode, OrderStr, null);
        }
        
        /// <remarks/>
        public void GetOrderListAsync(string cCode, string OrderStr, object userState) {
            if ((this.GetOrderListOperationCompleted == null)) {
                this.GetOrderListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderListOperationCompleted);
            }
            this.InvokeAsync("GetOrderList", new object[] {
                        cCode,
                        OrderStr}, this.GetOrderListOperationCompleted, userState);
        }
        
        private void OnGetOrderListOperationCompleted(object arg) {
            if ((this.GetOrderListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderListCompleted(this, new GetOrderListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Yannyo_Erp_DataEngine/GetStoresList", RequestNamespace="Yannyo_Erp_DataEngine", ResponseNamespace="Yannyo_Erp_DataEngine", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetStoresList(string cCode) {
            object[] results = this.Invoke("GetStoresList", new object[] {
                        cCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoresListAsync(string cCode) {
            this.GetStoresListAsync(cCode, null);
        }
        
        /// <remarks/>
        public void GetStoresListAsync(string cCode, object userState) {
            if ((this.GetStoresListOperationCompleted == null)) {
                this.GetStoresListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoresListOperationCompleted);
            }
            this.InvokeAsync("GetStoresList", new object[] {
                        cCode}, this.GetStoresListOperationCompleted, userState);
        }
        
        private void OnGetStoresListOperationCompleted(object arg) {
            if ((this.GetStoresListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoresListCompleted(this, new GetStoresListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProductListCompletedEventHandler(object sender, GetProductListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProductOrderListCompletedEventHandler(object sender, GetProductOrderListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductOrderListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductOrderListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderListCompletedEventHandler(object sender, GetOrderListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStoresListCompletedEventHandler(object sender, GetStoresListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoresListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoresListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591