// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Yannyo.Web {
	
	
	public partial class install_step_four {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
	}
}
